# Generated by Django 3.1.5 on 2021-02-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Persons',
        ),
    ]
