# Generated by Django 3.1.5 on 2021-02-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_persons_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persons',
            new_name='Person',
        ),
    ]
