# Generated by Django 3.0.8 on 2020-09-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.CharField(default='', max_length=200)),
                ('profile_pic', models.ImageField(default='', upload_to='tuts/images')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('inventor', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
