# Generated by Django 3.0.8 on 2020-09-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineers',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
